[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
depends = ['deoplete.nvim']
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'deoplete-jedi.vim'
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'jedi-vim.vim'
'''

[[plugins]]
repo = 'LaTeX-Box-Team/LaTeX-Box'
on_ft = ['tex', 'plaintex']
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'latex-box.vim'
'''

[[plugins]]
repo = 'hallison/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'skanehira/preview-markdown.vim'  # Usage :PreviewMarkdown
on_ft = ['md']
# need to install mdr binary from https://github.com/MichaelMure/mdr
